apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clouddns-nat-helper.fullname" . }}
  labels:
    {{- include "clouddns-nat-helper.labels" . | nindent 4  }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "clouddns-nat-helper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations  }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end  }}
      labels:
        {{- include "clouddns-nat-helper.selectorLabels" . | nindent 8  }}
    spec:
      {{- with .Values.imagePullSecrets  }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end  }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8  }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["clouddns-nat-helper"]
          args:
            # Source configuration
            - --source={{ .Values.ipv4Source }}
            {{- if eq .Values.ipv4Source "hostname"  }}
            {{- if .Values.hostname.name  }}
            - --ipv4-hostname={{ .Values.hostname.name }}
            {{- end  }}
            {{- if .Values.hostname.dnsServers  }}
            - --ipv4-hostname-dns-servers={{ join "," .Values.hostname.dnsServers }}
            {{- end  }}
            {{- end  }}
            {{- if eq .Values.ipv4Source "fixed"  }}
            - --ipv4-fixed-address={{ .Values.fixed.address }}
            {{- end  }}
            # Provider configuration
            - --provider={{- .Values.provider }}
            {{- if eq .Values.provider "cloudflare"  }}
            - --cloudflare-proxied={{ .Values.cloudflare.proxied }}
            {{- end  }}
            # Misc settings
            {{- if .Values.registry.tenant  }}
            - --registry-tenant={{ .Values.registry.tenant }}
            {{- end  }}
            {{- if .Values.loglevel  }}
            - --loglevel={{ .Values.loglevel }}
            {{- end  }}
            {{- if .Values.interval  }}
            - --interval={{ .Values.interval }}
            {{- end  }}
            {{- if .Values.policy  }}
            - --policy={{ .Values.policy }}
            {{- end  }}
            {{- if .Values.ttl  }}
            - --record-ttl={{ .Values.ttl }}
            {{- end  }}
          env:
            - name: CLOUDDNS_NAT_CLOUDFLARE_API_TOKEN
              valueFrom:
                secretKeyRef:
                    name: {{ include "clouddns-nat-helper.fullname" . }}
                    key: cloudflare_api_token
                    optional: true
          resources:
            {{- toYaml .Values.resources | nindent 12  }}
      {{- with .Values.nodeSelector  }}
      nodeSelector:
        {{- toYaml . | nindent 8  }}
      {{- end  }}
      {{- with .Values.affinity  }}
      affinity:
        {{- toYaml . | nindent 8  }}
      {{- end  }}
      {{- with .Values.tolerations  }}
      tolerations:
        {{- toYaml . | nindent 8  }}
      {{- end  }}
